# Makefile pour projet Pokémon

# Nom de l'exécutable
EXEC = pokemon_game

# Compilateur
CXX = g++

# Options de compilation (ajoute -Wall pour voir les warnings)
CXXFLAGS = -std=c++11 -Wall

# Fichiers source
SRC = Menu.cpp Pokemon.cpp Entraineur.cpp 

# Fichiers objet (générés automatiquement à partir des sources)
OBJ = $(SRC:.cpp=.o)

# Règle par défaut
all: $(EXEC)

# Générer l'exécutable
$(EXEC): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(EXEC) $(OBJ)

# Générer les fichiers .o
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Nettoyer les fichiers objets et l'exécutable
clean:
	rm -f $(OBJ) $(EXEC)

# Exécuter le programme
run: $(EXEC)
	./$(EXEC)
